{% set version = "0.2.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-survxai
  version: {{ version|replace("-", "_") }}

source:
  fn: survxai_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/survxai_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/survxai/survxai_{{ version }}.tar.gz
  sha256: 190349434519099233d576232f277f0b4cfa85b1c343e1d5fd72927282292f26

build:
  noarch: generic
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-breakdown
    - r-ggplot2
    - r-pec
    - r-prodlim
    - r-scales
    - r-survival
    - r-survminer
  run:
    - r-base
    - r-breakdown
    - r-ggplot2
    - r-pec
    - r-prodlim
    - r-scales
    - r-survival
    - r-survminer

test:
  commands:
    - $R -e "library('survxai')"           # [not win]
    - "\"%R%\" -e \"library('survxai')\""  # [win]

about:
  home: https://mi2datalab.github.io/survxai/
  license: GPL
  summary: "Survival models may have very different structures. This package contains functions  for creating a unified representation of a survival models, which can be further processed by various  survival explainers. Tools implemented in 'survxai' help to understand how input variables are used in  the model and what\
    \ impact do they have on the final model prediction. Currently, four explanation methods are implemented.  We can divide them into two groups: local and global."
  license_family: GPL
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
