# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "FdLlS08B0Im2gJ5iEpCvOk2US+uyn4iSgUMwBM+vWvbtDJYwWXP/2iHnjaFvrMm9txSKdrTsmUWdR8FLOFE6qS9woOD9yx7BTtY35Zn1UR7xz8xQanSdhEpgR7TPI6XL0sM1nX9QECphpal6LtSNUwNk36Q4vn3zE+bIpaUn47UQDmUa/U+wavqSZxs01Ofg186qKLyfdjzUzd/FiWKR8H5NgPzJC60B0DueV6Z/SfR/49hH6mVI84DIcGzxp7kahuBFuqzbrvQi38byKpMJbDW4+8KP8CiKOFzXJUyUnHzib9Q5b3G19ewZYo+f4WD2Rp2pMPE+g/qZDq1NJQeGG+CSoYQVRf0hLzDvdIxJF3cFhsPkbCed/cYBe8EFUrYSz5QUVp/hE7OFCBDbJe8zvdlEaDdMBI8IoTYIrGUACBQ27v+00lg+54nbm6qQY9oNpUyx32oEhdGB0OZq+4rZNDMrngISSQhKEuNpPVROyDetaw9Gh0ZRXE9IMBwTp0mxcq5VvhfO3KNc3yfD8t0bWr/e8IqXuc+1l9lyHEC4KVkha/CZ34idygSpKEX9jZ9kpFS/oDw0Q7v70MdnlWdHaB0R5cI5ZLNk9mpGbmrqD7ICdIHMAAULyYq4yelv0CDBtJYjeZ/RH9Fm6pm8GN0f/57oIczJd/TE0AS4Ceapjpw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
