appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: FdLlS08B0Im2gJ5iEpCvOk2US+uyn4iSgUMwBM+vWvbtDJYwWXP/2iHnjaFvrMm9txSKdrTsmUWdR8FLOFE6qS9woOD9yx7BTtY35Zn1UR7xz8xQanSdhEpgR7TPI6XL0sM1nX9QECphpal6LtSNUwNk36Q4vn3zE+bIpaUn47UQDmUa/U+wavqSZxs01Ofg186qKLyfdjzUzd/FiWKR8H5NgPzJC60B0DueV6Z/SfR/49hH6mVI84DIcGzxp7kahuBFuqzbrvQi38byKpMJbDW4+8KP8CiKOFzXJUyUnHzib9Q5b3G19ewZYo+f4WD2Rp2pMPE+g/qZDq1NJQeGG+CSoYQVRf0hLzDvdIxJF3cFhsPkbCed/cYBe8EFUrYSz5QUVp/hE7OFCBDbJe8zvdlEaDdMBI8IoTYIrGUACBQ27v+00lg+54nbm6qQY9oNpUyx32oEhdGB0OZq+4rZNDMrngISSQhKEuNpPVROyDetaw9Gh0ZRXE9IMBwTp0mxcq5VvhfO3KNc3yfD8t0bWr/e8IqXuc+1l9lyHEC4KVkha/CZ34idygSpKEX9jZ9kpFS/oDw0Q7v70MdnlWdHaB0R5cI5ZLNk9mpGbmrqD7ICdIHMAAULyYq4yelv0CDBtJYjeZ/RH9Fm6pm8GN0f/57oIczJd/TE0AS4Ceapjpw=}
bot:
  automerge: true
